### ISSUE TITLE
Provide a way to opt out of clang-format on save

### ISSUE THREAD

**Issue by vmalloc** [drrlvn/.emacs.d#73]
Apparently some projects have a `.clang-format` in their root, but it gets applied selectively. This means saving any file in that project triggers possibly undesired effects.
It also means that if someone doesn't have clang-format installed, he or she cannot save their work until they get it installed, which is annoying.

**Comment by drrlvn** [comment]
I'll fix the saving function so that it does nothing if clang-format is not available.

To selectively disable/enable clang-format, how do you want to control for which files clang-format is run? Would you want a buffer-local variable? Or are you asking for a way to disable it entirely?

**Comment by vmalloc** [comment]
I'm fine with a way to disable it for a current buffer... It's not something I expect to be doing a lot...

**Comment by drrlvn** [comment]
Would adding a `// clang-format off` comment at the start of the file work? If the project is formatted but specific files aren't then this seems like the most robust solution.

**Comment by vmalloc** [comment]
Adding it works, but I don't want to be changing too much in the original file. I think there should be a way of disabling it without making me push superfluous additions to a code that's not mine, just to overcome an opinionated setup I happen to be using...

**Comment by drrlvn** [comment]
You can now set `my/disable-clang-format-on-save` to `t` for the problematic buffer. Also, as mentioned, if clang-format isn't available things should not break.

**Comment by vmalloc** [comment]
👍 thanks!
